//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MirKvartir.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MirKvartir.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срочно сдам квартиру в хорошем доме! Срок сдачи - от 1 месяца. В квартире есть все необходимое: микроволновка, холодильник, стиральная машина. Рассмотрю всех!
        ///
        ///Уютная квартира, с качественной мебелью и техникой. Кухня полностью укомплектована, есть вся техника. В ванной стиральная машина. Сдается на длительный срок порядочным платежеспособным людям. Посмотреть можно в любой день.
        ///
        ///Срочно сдам кварнтиру. на длительный срок. Все для комфортного проживания, кровать, шкаф, холодильник, микроволновка, плита, [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string descriptionOnes {
            get {
                return ResourceManager.GetString("descriptionOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СРОЧНО! Сдаю комнату БЕЗ СОСЕДЕЙ, т.к. вторая комната закрыта под наши вещи, поскольку вещи девать некуда комната сдаваться не планируется минимум 5 лет! И сдавать будем по цене комнаты. Для проживания есть всё самое необходимое. Рассмотрим любые варианты. Агентам не беспокоить!
        ///
        ///Сдаю комнату БЕЗ СОСЕДЕЙ, т.к. вторая комната закрыта под хозяйские вещи. Для проживания есть всё самое необходимое. Рассмотрим любые варианты. Агентам не беспокоить!
        ///
        ///Сдаю комнату БЕЗ СОСЕДЕЙ, вторая комната закрыта под вещи.  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string descriptionRoom {
            get {
                return ResourceManager.GetString("descriptionRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {
        ///  &quot;estateId&quot;: &quot;8f03b139-07b9-4a81-badb-159e0501f9c0&quot;,
        ///  &quot;mainId&quot;: 0,
        ///  &quot;created&quot;: &quot;0001-01-01&quot;,
        ///  &quot;updated&quot;: 0,
        ///  &quot;rentPeriods&quot;: [
        ///    {
        ///      &quot;disabled&quot;: false,
        ///      &quot;group&quot;: null,
        ///      &quot;selected&quot;: false,
        ///      &quot;text&quot;: &quot;в месяц&quot;,
        ///      &quot;value&quot;: &quot;Month&quot;
        ///    },
        ///    {
        ///      &quot;disabled&quot;: false,
        ///      &quot;group&quot;: null,
        ///      &quot;selected&quot;: false,
        ///      &quot;text&quot;: &quot;в день&quot;,
        ///      &quot;value&quot;: &quot;Day&quot;
        ///    }
        ///  ],
        ///  &quot;allEstateTypes&quot;: [
        ///    {
        ///      &quot;disabled&quot;: false,
        ///      &quot;group&quot;: null,
        ///      &quot;selected [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string jsonText {
            get {
                return ResourceManager.GetString("jsonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {        ///
        ///  &quot;estateId&quot;: &quot;b4f2b7ea-56f7-4ad7-a52d-785d629b2126&quot;,        ///
        ///  &quot;mainId&quot;: 0,        ///
        ///  &quot;created&quot;: &quot;0001-01-01&quot;,        ///
        ///  &quot;updated&quot;: 0,        ///
        ///  &quot;rentPeriods&quot;: [        ///
        ///    {        ///
        ///      &quot;disabled&quot;: false,        ///
        ///      &quot;group&quot;: null,        ///
        ///      &quot;selected&quot;: false,        ///
        ///      &quot;text&quot;: &quot;в месяц&quot;,        ///
        ///      &quot;value&quot;: &quot;Month&quot;        ///
        ///    },        ///
        ///    {        ///
        ///      &quot;disabled&quot;: false,        ///
        ///      &quot;group&quot;: null,        ///
        ///      &quot;selected&quot;: false,        ///
        ///      &quot;text&quot;: &quot;в день&quot;,        ///
        ///      &quot;value&quot;: &quot;Day&quot;        ///
        ///    }        ///
        ///  ],        ///
        ///  &quot;allEstateTypes&quot;: [        ///
        ///    {        ///
        ///      &quot;disabled&quot;: false,        ///
        ///      &quot;group&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string jsonText1 {
            get {
                return ResourceManager.GetString("jsonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {        ///
        ///  &quot;estateId&quot;: &quot;ed842ddb-b9fe-4668-8372-9db983bf60bc&quot;,        ///
        ///  &quot;mainId&quot;: 0,        ///
        ///  &quot;created&quot;: &quot;0001-01-01&quot;,        ///
        ///  &quot;updated&quot;: 0,        ///
        ///  &quot;rentPeriods&quot;: [        ///
        ///    {        ///
        ///      &quot;disabled&quot;: false,        ///
        ///      &quot;group&quot;: null,        ///
        ///      &quot;selected&quot;: false,        ///
        ///      &quot;text&quot;: &quot;в месяц&quot;,        ///
        ///      &quot;value&quot;: &quot;Month&quot;        ///
        ///    },        ///
        ///    {        ///
        ///      &quot;disabled&quot;: false,        ///
        ///      &quot;group&quot;: null,        ///
        ///      &quot;selected&quot;: false,        ///
        ///      &quot;text&quot;: &quot;в день&quot;,        ///
        ///      &quot;value&quot;: &quot;Day&quot;        ///
        ///    }        ///
        ///  ],        ///
        ///  &quot;allEstateTypes&quot;: [        ///
        ///    {        ///
        ///      &quot;disabled&quot;: false,        ///
        ///      &quot;group&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string jsonText2 {
            get {
                return ResourceManager.GetString("jsonText2", resourceCulture);
            }
        }
    }
}
